name: "CI"
on:
  push:
  pull_request:

jobs:
  find-supported-colors:
    runs-on: ubuntu-latest

    outputs:
      colors: ${{ steps.colors.outputs.colors }}

    steps:
      - uses: actions/checkout@v4
      - name: Find Colors
        id: colors
        run: |
          echo -n "colors=" >> "$GITHUB_OUTPUT"
          ls .github/workflows/palettes/*.conf | sed -E 's|.*/([a-z]+).conf|"\1"|' | jq -c -s . >> "$GITHUB_OUTPUT"
  build:
    runs-on: ubuntu-latest
    needs:
      - find-supported-colors
    strategy:
      matrix:
        color: ${{ fromJSON(needs.find-supported-colors.outputs.colors) }}
    name: build ${{ matrix.color }} variant
    steps:
      - uses: actions/checkout@v4
      - name: Install System Dependencies
        run: |
          sudo apt install meson sassc inkscape
      - name: Generate ${{ matrix.color }} Variant
        env:
          color: ${{ matrix.color }}
        run: |
          .github/workflows/patch-colors "$color"
          meson setup --prefix=$(pwd)/target -Dcinnamon_version=5.4 -Dgnome_shell_version=45 build/
          meson install -C build
