name: "Build color variants"
on:
  push:
  pull_request:

jobs:
  red:
    name: generate red variants
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: meson sassc inkscape
      - name: build
        run: |
          .github/workflows/patch-colors red
          meson setup --prefix=$(pwd)/target -Dcinnamon_version=5.4 -Dgnome_shell_version=45 build/
          meson install -C build
