name: "Sync with main repo"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * 1"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Merge main repo changes
        run: |
          git config --global user.email "workflow@github.com"
          git config --global user.name "GitHub Workflow"
          git remote add main-repo https://github.com/jnsh/arc-theme.git
          git remote update
          git merge --allow-unrelated-histories main-repo/master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: Sync with main repo
          branch: fork-sync
          delete-branch: true
